#pragma once
#include <string>

namespace Verbeal::IO
{
	// The User Directory is for settings and configuration which the user would want portable
	std::string GetUserDataDirectory();

	// Local User Directory is for settings and configuration which is specific to the local machine
	std::string GetLocalUserDataDirectory();

	// Directory of logs generated by the application
	std::string GetLogsDirectory();
}